// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXhc0QEYv2l7NEBMLGAJi1CTJfc-XC3xM',
    appId: '1:901255983048:web:fade96da242a56e6161afd',
    messagingSenderId: '901255983048',
    projectId: 'classinsight-e7577',
    authDomain: 'classinsight-e7577.firebaseapp.com',
    storageBucket: 'classinsight-e7577.appspot.com',
    measurementId: 'G-7JE91CNC8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY5wUsbeWDRf5WsTENAkx_DH2qVSf_6Vk',
    appId: '1:901255983048:android:18542d69c052b7fe161afd',
    messagingSenderId: '901255983048',
    projectId: 'classinsight-e7577',
    storageBucket: 'classinsight-e7577.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCYFL6pPHtmHeFIbJNbfEThCcriIHQM6k',
    appId: '1:901255983048:ios:7246aeb2c9bd9a71161afd',
    messagingSenderId: '901255983048',
    projectId: 'classinsight-e7577',
    storageBucket: 'classinsight-e7577.appspot.com',
    iosBundleId: 'com.example.classinsight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCYFL6pPHtmHeFIbJNbfEThCcriIHQM6k',
    appId: '1:901255983048:ios:7246aeb2c9bd9a71161afd',
    messagingSenderId: '901255983048',
    projectId: 'classinsight-e7577',
    storageBucket: 'classinsight-e7577.appspot.com',
    iosBundleId: 'com.example.classinsight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXhc0QEYv2l7NEBMLGAJi1CTJfc-XC3xM',
    appId: '1:901255983048:web:d12ee2b2cef166ab161afd',
    messagingSenderId: '901255983048',
    projectId: 'classinsight-e7577',
    authDomain: 'classinsight-e7577.firebaseapp.com',
    storageBucket: 'classinsight-e7577.appspot.com',
    measurementId: 'G-CGF4YZR9YG',
  );
}
